export const cities = [
  { name: 'Москва', id: 'moscow' },
  { name: 'Санкт-Петербург', id: 'saint-petersburg' },
  { name: 'Новосибирск', id: 'novosibirsk' },
  { name: 'Екатеринбург', id: 'yekaterinburg' },
  { name: 'Казань', id: 'kazan' },
  { name: 'Нижний Новгород', id: 'nizhny-novgorod' },
  { name: 'Челябинск', id: 'chelyabinsk' },
  { name: 'Красноярск', id: 'krasnoyarsk' },
  { name: 'Самара', id: 'samara' },
  { name: 'Уфа', id: 'ufa' },
  { name: 'Ростов-на-Дону', id: 'rostov-na-donu' },
  { name: 'Омск', id: 'omsk' },
  { name: 'Воронеж', id: 'voronezh' },
  { name: 'Пермь', id: 'perm' },
  { name: 'Волгоград', id: 'volgograd' },
  { name: 'Краснодар', id: 'krasnodar' },
  { name: 'Тюмень', id: 'tyumen' },
  { name: 'Ижевск', id: 'izhevsk' },
  { name: 'Барнаул', id: 'barnaul' },
  { name: 'Ульяновск', id: 'ulyanovsk' },
  { name: 'Иркутск', id: 'irkutsk' },
  { name: 'Хабаровск', id: 'khabarovsk' },
  { name: 'Ярославль', id: 'yaroslavl' },
  { name: 'Владивосток', id: 'vladivostok' },
  { name: 'Махачкала', id: 'makhachkala' },
  { name: 'Томск', id: 'tomsk' },
  { name: 'Оренбург', id: 'orenburg' },
  { name: 'Кемерово', id: 'kemerovo' },
  { name: 'Новокузнецк', id: 'novokuznetsk' },
  { name: 'Рязань', id: 'ryazan' },
  { name: 'Астрахань', id: 'astrakhan' },
  { name: 'Набережные Челны', id: 'naberezhnye-chelny' },
  { name: 'Пенза', id: 'penza' },
  { name: 'Липецк', id: 'lipetsk' },
  { name: 'Тула', id: 'tula' },
  { name: 'Киров', id: 'kirov' },
  { name: 'Чебоксары', id: 'cheboksary' },
  { name: 'Калининград', id: 'kaliningrad' },
  { name: 'Курск', id: 'kursk' },
  { name: 'Улан-Удэ', id: 'ulan-ude' },
  { name: 'Ставрополь', id: 'stavropol' },
  { name: 'Тверь', id: 'tver' },
  { name: 'Магнитогорск', id: 'magnitogorsk' },
  { name: 'Сургут', id: 'surgut' },
  { name: 'Иваново', id: 'ivanovo' },
  { name: 'Брянск', id: 'bryansk' },
  { name: 'Якутск', id: 'yakutsk' },
  { name: 'Нижний Тагил', id: 'nizhny-tagil' },
  { name: 'Белгород', id: 'belgorod' },
  { name: 'Архангельск', id: 'arkhangelsk' },
];
