import type { Metadata } from "next";
import { Inter, Onest } from "next/font/google";
import "./globals.css";
import '../shared/styles/reset.css';
import '../shared/styles/main.scss';
import Header from "@/widgets/Header/Header";
import "/public/fonts/Transforma Mix/styles.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${onest.variable}  antialiased`}
      >
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
